### ISSUE TITLE
sm_120 issue

### ISSUE THREAD

**Issue by Terminator98** [nari-labs/dia#232]
I have just bought RTX 5060 Ti with VRAM of 16 GB but when I run the app using
```bash
uv run app.py
```
It gives me this
```bash
NVIDIA GeForce RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5060 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```
I've tried to download the latest `pytorch` version with cu128 but it doesn't work.

Any ideas?

**Comment by h0nyk** [comment]
I am also using a RTX 5060 Ti with VRAM of 16 GB 
Unfortunately your solution did not work for me.  
But I got it to work and explained my solution in https://github.com/nari-labs/dia/issues/260#issuecomment-3137940264

> **Solution:** Upgrade PyTorch and Torchaudio to version `2.7.0+cu128` and update the package index URL.
> 
> ### What to change in `pyproject.toml`
> Update the torch and torchaudio dependencies:
> 
> dependencies = [
>     # other dependencies ...
>     "torch==2.7.0+cu128",
>     "torchaudio==2.7.0+cu128",
>     # other dependencies ...
> ]
> Update the PyTorch package index:
> 
> ```
> [tool.uv.sources]
> torch = [
>   { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
> ]
> torchaudio = [
>   { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
> ]
> 
> [[tool.uv.index]]
> name = "pytorch-cu128"
> url = "https://download.pytorch.org/whl/cu128"
> explicit = true
> ```
> 
> Then run:
> 
> ```
> uv pip install
> ```
> 
> OR if you are using venv after it's creation you can just
> 
> ```
> pip uninstall torch torchaudio
> pip install torch==2.7.0+cu128 torchaudio==2.7.0+cu128 --index-url https://download.pytorch.org/whl/cu128
> ```
